curl ../avalos-activistas/ --insecure -o "files/View “Avalos – Activistas”" 
curl ../avalos-seminario-testigo-i-espanol/ --insecure -o "files/View “Avalos Seminario Testigo I (Español)”" 
curl ../local-community-members/ --insecure -o "files/View “El Paso – Other Local Community Members”" 
curl ../professionals-esp-in-environmental-health-fields-3/ --insecure -o "files/View “Minatitlán Coatzacoalcos–Profesionales en el medio ambiente y la salud”" 
curl ../workers-in-local-industry-4/ --insecure -o "files/View “Minatitlán Coatzacoalcos–Los trabajadores de la industria local”" 
curl ../managers-and-professionals-in-local-industry-3/ --insecure -o "files/View “Minatitlán Coatzacoalcos–El gerente y los profesionales de la industria local”" 
curl ../becoming-active-4/ --insecure -o "files/View “Minatitlán Coatzacoalcos–Activismo, Movilización, Conflicto”" 
curl ../keeping-things-quiet-4/ --insecure -o "files/View “Minatitlán Coatzacoalcos–Guardando silencio”" 
curl ../remembering-when-you-didnt-know-4/ --insecure -o "files/View “Minatitlán Coatzacoalcos–Recordando lo que usted no sabía”" 
curl ../coming-to-know-4/ --insecure -o "files/View “Minatitlán Coatzacoalcos–Llegando a conocer”" 
curl ../managers-and-professions-in-local-industry/ --insecure -o "files/View “El Paso – Managers and Professionals in Local Industry”" 
curl ../becoming-active-2/ --insecure -o "files/View “El Paso – Becoming Active, Mobilizing, and Clashing”" 
curl ../keeping-things-quiet-2/ --insecure -o "files/View “El Paso – Keeping Things Quiet”" 
curl ../remembering-when-you-didnt-know-2/ --insecure -o "files/View “El Paso – Remembering When You Didn’t Know”" 
curl ../coming-to-know-2/ --insecure -o "files/View “El Paso – Coming to Know”" 
curl ../seminario-completo/ --insecure -o "files/View “Minatitlán Coatzacoalcos Seminario Testigo”" 
curl ../avalos-witness-seminar-ii/ --insecure -o "files/View “Avalos Seminario Testigo II (Español)”" 
curl ../avalos-witness-seminar-i/ --insecure -o "files/View “Avalos Witness Seminar I”" 
curl ../local/ --insecure -o "files/View “El Paso–Activists – Local”" 
curl ../workers-in-local-industry/ --insecure -o "files/View “El Paso – Workers in Local Industry”" 
curl ../port-arthur-government-officials/ --insecure -o "files/View “Port Arthur – Government officials:”" 
curl ../port-arthur-activists-local/ --insecure -o "files/View “Port Arthur – Activists—local:”" 
curl ../port-arthur-professionals-in-environmental-health-and-related-fields-local/ --insecure -o "files/View “Port Arthur – Professionals in environmental, health, and related fields—local:”" 
curl ../port-arthur-local-community-members/ --insecure -o "files/View “Port Arthur – Local community members:”" 
curl ../port-arthur-workers-and-unions-in-local-industry/ --insecure -o "files/View “Port Arthur – Workers and unions in local industry:”" 
curl ../port-arthur-managers-and-professionals-in-local-industry/ --insecure -o "files/View “Port Arthur – Managers and professionals in local industry:”" 
curl ../port-arthur-becoming-active-mobilizing-and-conflict/ --insecure -o "files/View “Port Arthur – Becoming active; Mobilizing and conflict:”" 
curl ../port-arthur-keeping-things-quiet/ --insecure -o "files/View “Port Arthur – Keeping things quiet:”" 
curl ../port-arthur-%e2%80%a2-coming-to-know/ --insecure -o "files/View “Port Arthur – Remembering when you didn’t know:”" 
curl ../3739-2/ --insecure -o "files/View “Proof Of Concept [Port Arthur]”" 
curl ../this-is-a-test/ --insecure -o "files/View “This is a Test”" 
curl ../port-arthur-tx-witness-seminar/ --insecure -o "files/View “Port Arthur, TX Witness Seminar”" 
curl ../avalos-miembros-de-la-comunidad/ --insecure -o "files/View “Avalos – Otros miembros de la comunidad”" 
curl ../dialogo-con-el-seminario-en-el-paso/ --insecure -o "files/View “Diálogo con el seminario en El Paso”" 
curl ../avalos-recordando-lo-que-usted-no-sabia/ --insecure -o "files/View “Avalos – Recordando lo que usted no sabía”" 
curl ../avalos-los-trabajadores-de-la-industria-local/ --insecure -o "files/View “Avalos – Los Trabajadores de la Industria Local”" 
curl ../avalos-profesionales-en-el-medio-ambiente-la-salud-y-campos-afines/ --insecure -o "files/View “Avalos – Profesionales en el medio ambiente , la salud y campos afines”" 
curl ../avalos-el-gerente-y-los-profesionales-de-la-industria-local/ --insecure -o "files/View “Avalos – El gerente y los profesionales de la industria local”" 
curl ../avalos-guardando-silencio/ --insecure -o "files/View “Avalos – Guardando Silencio”" 
curl ../avalos-llegando-a-conocer/ --insecure -o "files/View “Avalos – Llegando a conocer”" 
curl ../el-paso-wittness-seminar-ii/ --insecure -o "files/View “El Paso Witness Seminar II”" 
curl ../el-paso-wittness-seminar-i/ --insecure -o "files/View “El Paso Witness Seminar I”" 
